src/HolidayLeave.Web/ViewModels/HolidayLeave/HolidayLeaveCreateViewModel.cs
using HolidayLeave.Core.Infrastructure.AutoMapper;
using HolidayLeave.Data.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HolidayLeave.Web.ViewModels.HolidayLeave
{
    public class HolidayLeaveCreateViewModel : IValidatableObject
    {
        [Required(ErrorMessage = "Pole nie może być puste")]
        [Display(Name = "Imię")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Pole nie może być puste")]
        [Display(Name = "Data od")]
        public DateTime? DateFrom { get; set; }

        [Required(ErrorMessage = "Pole nie może być puste")]
        [Display(Name = "Data do")]
        public DateTime? DateTo { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DateFrom < DateTime.Now)
            {
                yield return new ValidationResult(
                    errorMessage: "Pole ‘Data od’ może zawierać tylko daty z przyszłości",
                    memberNames: new[] { "DateFrom" });
            }

            if (DateTo < DateFrom)
            {
                yield return new ValidationResult(
                    errorMessage: "Pole ‘Data do’ może zawierać tylko daty późniejsze od ‘Data od’",
                    memberNames: new[] { "DateTo" });
            }
        }
    }

    public class HolidayLeaveCreateViewModelProfile : AutoMapperProfile
    {
        public HolidayLeaveCreateViewModelProfile()
        {
            CreateMap<HolidayLeaveModel, HolidayLeaveCreateViewModel>();
        }
    }    
}

src/HolidayLeave.Web/ViewModels/HolidayLeave/HolidayLeaveDetailsModel.cs
using HolidayLeave.Core.Infrastructure.AutoMapper;
using HolidayLeave.Data.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HolidayLeave.Web.ViewModels.HolidayLeave
{

    public class HolidayLeaveDetailsModel
    {
        public List<HolidayLeaveRowViewModel> HolidayLeaves { get; set; }

        [Display(Name = "Data")]
        public DateTime? Date { get; set; }
    }

    public class HolidayLeaveRowViewModel
    {
        public string Name { get; set; }

        public DateTime DateFrom { get; set; }

        public DateTime DateTo { get; set; }     
    }

    public class HolidayLeaveDetailsModelProfile : AutoMapperProfile
    {
        public HolidayLeaveDetailsModelProfile()
        {
            CreateMap<HolidayLeaveModel, HolidayLeaveRowViewModel>();
        }
    }
}

src/HolidayLeave.Web/Controllers/BaseController.cs
using System.Web.Mvc;

namespace HolidayLeave.Web.Controllers
{
    public class BaseController : Controller
    {
        protected void SetTemporaryMessage(string temporaryMessage, string temporaryType)
        {
            TempData["TemporaryMessage"] = temporaryMessage;
            TempData["TemporaryType"] = temporaryType;
        }

        public static class TemporaryType
        {
            public static string Danger = "alert alert-danger";
            public static string Succes = "alert alert-success";
            public static string Warning = "alert alert-warning";
        }
    }
}

src/HolidayLeave.Web/Controllers/HolidayLeaveController.cs
using AutoMapper;
using HolidayLeave.Data.Models;
using HolidayLeave.Service.Services;
using HolidayLeave.Web.ViewModels.HolidayLeave;
using System.Collections.Generic;
using System.Web.Mvc;

namespace HolidayLeave.Web.Controllers
{
    public class HolidayLeaveController : BaseController
    {
        private const string SuccesAddHolidayLeave = "Dodano urlop";
        private const string RemoveHolidayLeave = "Urolpy zostały usunięte";

        private readonly IHolidayLeaveService _holidayLeaveService;

        public HolidayLeaveController(IHolidayLeaveService holidayLeaveService)
        {
            _holidayLeaveService = holidayLeaveService;
        }

        [HttpGet]
        public ActionResult Create() =>
            View(new HolidayLeaveCreateViewModel());

        [HttpPost]
        public ActionResult Create(HolidayLeaveCreateViewModel holidayLeaveCreateModel)
        {
            if (ModelState.IsValid)
            {
                var holidayLeaveModel = Mapper.Map<HolidayLeaveModel>(holidayLeaveCreateModel);
                _holidayLeaveService.Add(holidayLeaveModel);
                SetTemporaryMessage(SuccesAddHolidayLeave, TemporaryType.Succes);

                return RedirectToAction("Create");
            }

            return View(holidayLeaveCreateModel);
        }

        [HttpGet]
        public ActionResult Details()
        {
            var data = new HolidayLeaveDetailsModel
            {
                HolidayLeaves =
                   Mapper.Map<List<HolidayLeaveRowViewModel>>(
                       _holidayLeaveService
                           .GetHolidayLeaves())
            };

            return View(data);
        }

        [HttpPost]
        public ActionResult Details(HolidayLeaveDetailsModel holidayLeaveDetailsModel)
        {
            if (ModelState.IsValid)
            {
                var data = new HolidayLeaveDetailsModel
                {
                    HolidayLeaves =
                        Mapper.Map<List<HolidayLeaveRowViewModel>>(
                           _holidayLeaveService
                               .GetHolidayLeavesBy(holidayLeaveDetailsModel.Date))
                };
                return View(data);
            }
            return View(holidayLeaveDetailsModel);
        }

        [HttpGet]
        public ActionResult RemoveAllHolidayLeave()
        {
            _holidayLeaveService
                .Clear();

            SetTemporaryMessage(RemoveHolidayLeave, TemporaryType.Succes);

            return RedirectToAction("Details");
        }
    }
}

src/HolidayLeave.Web/Views/HolidayLeave/Create.cshtml
@model HolidayLeave.Web.ViewModels.HolidayLeave.HolidayLeaveCreateViewModel

@Scripts.Render("~/Scripts/jquery.validate.js")
@Scripts.Render("~/Scripts/jquery.validate.unobtrusive.js")
@Scripts.Render("~/Scripts/jquery-ui-1.12.1.min.js")

@Styles.Render("~/Content/themes/base/jquery-ui.min.css")

<div class="col-md-10">
    <h2>Dodaj urlop</h2>
</div>

@using (Html.BeginForm("Create", "HolidayLeave", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    @Html.AntiForgeryToken()

    <div class="form-horizontal container">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-3 ">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group ">
            <div class='col-md-3'>
                @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label" })

                <div class="input-group" style="display: block">
                    @Html.EditorFor(model => model.DateFrom, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control date-picker",
                            @placeholder = "yyyy.mm.dd",
                            @Style = "width:80%"
                        }
                     })
                    <span class="input-group-addon form-control" style="width: 20%;">
                        <i class="glyphicon glyphicon-calendar"></i>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.DateFrom, string.Empty, new { @class = "text-danger" })
            </div>            
        </div>
        <div class="form-group">
            <div class='col-md-3'>
                @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label" })

                <div class="input-group" style="display: block">
                    @Html.EditorFor(model => model.DateTo, new
                    {
                        htmlAttributes = new
                        {
                            @class = "form-control date-picker",
                            @placeholder = "yyyy.mm.dd",
                            @Style = "width:80%"
                        }
                    })
                    <span class="input-group-addon form-control" style="width: 20%;">
                        <i class="glyphicon glyphicon-calendar"></i>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.DateTo, string.Empty, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group ">
            <div class="row col-md-3 ">
                <div class="col-md-4">
                    <input type="submit" value="Dodaj" class="btn btn-success" />
                </div>
                <div class="col-md-4">
                    <input type="button" value="Koniec" class="btn btn-info" onclick="location.href='@Url.Action("Details", "HolidayLeave")'" />
                </div>
            </div>
        </div>
    </div>

}

@Scripts.Render("~/Scripts/app/views/holidayLeave/calendar.js")

src/HolidayLeave.Web/Views/HolidayLeave/Details.cshtml
@model HolidayLeave.Web.ViewModels.HolidayLeave.HolidayLeaveDetailsModel

@Scripts.Render("~/Scripts/jquery.validate.js")
@Scripts.Render("~/Scripts/jquery.validate.unobtrusive.js")
@Scripts.Render("~/Scripts/jquery-ui-1.12.1.min.js")

@Styles.Render("~/Content/themes/base/jquery-ui.min.css")

<div class="col-md-10">
    <h2>Wynik</h2>
</div>

@using (Html.BeginForm("Details", "HolidayLeave", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    @Html.AntiForgeryToken()

    <div class="form-horizontal container">
        <div class="col-md-5">
            <div class="form-group ">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                <div class="input-group" style="display: block">
                    @Html.EditorFor(model => model.Date, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control date-picker",
                       @placeholder = "yyyy.mm.dd",
                       @Value = string.Empty,
                       @Style = "width:90%"
                   }
               })
                    <span class="input-group-addon form-control" style="width: 10%;">
                        <i class="glyphicon glyphicon-calendar"></i>
                    </span>
                </div>
                <div class="col-md-12">
                    @Html.ValidationMessageFor(model => model.Date, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <div class="form-group ">
                    <div class="row col-md-6 ">
                        <div class="col-md-2">
                            <input type="submit" value="Szukaj" class="btn btn-info" />
                        </div>
                        <div class="col-md-3">
                            <input type="button" value="Dodaj urlop" class="btn btn-success" onclick="location.href='@Url.Action("Create", "HolidayLeave")'" />
                        </div>
                        <div class="col-md-3">
                            <input type="button" value="Wyczyść urlopy" class="btn btn-warning" onclick="location.href='@Url.Action("RemoveAllHolidayLeave", "HolidayLeave")'" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                @(Html
                    .Grid(Model.HolidayLeaves)
                    .Build(columns =>
                    {
                        columns.Add().RenderedAs((model, row) => row + 1).Titled("Lp");
                        columns.Add(model => model.Name).Titled("Imię");
                        columns.Add(model => model.DateFrom.ToString("yyyy.MM.dd")).Titled("Data od");
                        columns.Add(model => model.DateTo.ToString("yyyy.MM.dd")).Titled("Data do");
                    })
                    .Empty("Brak Danych")
                    .Filterable()
                )
            </div>
        </div>
    </div>
}

@Scripts.Render("~/Scripts/app/views/holidayLeave/calendar.js")

src/HolidayLeave.Web/Views/Shared/MvcGrid/_Grid.cshtml
@using NonFactors.Mvc.Grid;
@using System.Web.Mvc;

@model IGrid

<div id="@Model.Id" class="mvc-grid mvc-grid-@(Model.FilterMode.ToString().ToLower())-mode" data-name="@Model.Name" data-filter-mode="@Model.FilterMode" data-source-url="@Model.SourceUrl">
    <table@(Model.Attributes)>
        <thead>
            <tr class="mvc-grid-headers@(Model.FilterMode == GridFilterMode.Header ? " mvc-grid-row-filters" : "")">
            @foreach (IGridColumn column in Model.Columns)
            {
                String hidden = column.IsHidden ? "mvc-grid-hidden" : null;
                String sortable = column.Sort.IsEnabled == true ? "sortable" : null;
                Boolean filterApplied = (column.Filter.First ?? column.Filter.Second) != null;
                String filterable = column.Filter.IsEnabled == true && !String.IsNullOrEmpty(column.Filter.Name) ? "filterable" : null;

                <th class="@column.CssClasses @filterable @sortable @column.Sort.Order.ToString().ToLower() @hidden" data-name="@column.Name" data-filter="@column.Filter.IsEnabled" data-filter-applied="@filterApplied" data-filter-name="@column.Filter.Name" data-filter-type="@column.Filter.Type" data-filter-default-method="@column.Filter.DefaultMethod" data-sort="@column.Sort.IsEnabled" data-sort-order="@column.Sort.Order" data-sort-first="@column.Sort.FirstOrder">
                @if (column.Filter.IsEnabled == true && !String.IsNullOrEmpty(column.Filter.Name) && Model.FilterMode != GridFilterMode.Row)
                {
                    if (Model.FilterMode == GridFilterMode.Header)
                    {
                        String title = column.Title as String ?? "";
                        Int32 size = title.Length > 0 ? title.Length : 20;
                        String[] values = column.Filter.First != null ? column.Filter.First.Values ?? new String[0] : new String[0];
                        values = column.Filter.Options.Any() ? column.Filter.Options.Where(option => values.Contains(option.Value)).Select(option => option.Text).ToArray() : values;

                    <div>
                        @if (column.Filter.Options.Any())
                        {
                            values = column.Filter.Options.Where(option => values.Contains(option.Value)).Select(option => option.Text).ToArray();

                        <input class="mvc-grid-value" value="@String.Join(", ", values)" size="@size" placeholder="@column.Title" tabindex="-1" readonly />
                        }
                        else
                        {
                        <input class="mvc-grid-value" value="@String.Join(", ", values)" size="@size" placeholder="@column.Title" />
                        }
                    </div>
                    }
                    else
                    {
                    <span class="mvc-grid-title">@column.Title</span>
                    }

                    <select class="mvc-grid-options">
                        @foreach (SelectListItem option in column.Filter.Options)
                        {
                        <option value="@option.Value">@option.Text</option>
                        }
                    </select>

                    if (column.Sort.IsEnabled == true)
                    {
                    <button type="button" class="mvc-grid-sort"></button>
                    }

                    <button type="button" class="mvc-grid-filter @(filterApplied ? "applied" : "")"></button>
                }
                else
                {
                    <span class="mvc-grid-title">@column.Title</span>

                    if (column.Sort.IsEnabled == true)
                    {
                    <button type="button" class="mvc-grid-sort"></button>
                    }
                }
                </th>
            }
            </tr>
        @if (Model.FilterMode == GridFilterMode.Row)
        {
            <tr class="mvc-grid-row-filters">
            @foreach (IGridColumn column in Model.Columns)
            {
                String hidden = column.IsHidden ? "mvc-grid-hidden" : null;

                if (column.Filter.IsEnabled == true && !String.IsNullOrEmpty(column.Filter.Name))
                {
                    String filterApplied = (column.Filter.First ?? column.Filter.Second) != null ? "applied" : "";

                <th class="filterable @column.CssClasses @hidden">
                    <div>
                    @if (column.Filter.Options.Any())
                    {
                        if (column.Filter.Type == GridFilterType.Multi)
                        {
                            String[] values = column.Filter.First != null ? column.Filter.First.Values ?? new String[0] : new String[0];
                            values = column.Filter.Options.Where(option => values.Contains(option.Value)).Select(option => option.Text).ToArray();

                        <input class="mvc-grid-value" value="@String.Join(", ", values)" tabindex="-1" readonly />

                        <select class="mvc-grid-options">
                            @foreach (SelectListItem option in column.Filter.Options)
                            {
                            <option value="@option.Value">@option.Text</option>
                            }
                        </select>
                        }
                        else
                        {
                        <select class="mvc-grid-value">
                            @foreach (SelectListItem option in column.Filter.Options)
                            {
                                if (column.Filter.First != null && column.Filter.First.Values.Contains(option.Value))
                                {
                            <option value="@option.Value" selected>@option.Text</option>
                                }
                                else
                                {
                            <option value="@option.Value">@option.Text</option>
                                }
                            }
                        </select>
                        }
                    }
                    else
                    {
                        <input class="mvc-grid-value" value="@(column.Filter.First != null ? column.Filter.First.Values[0] : "")" />
                    }
                        <button type="button" class="mvc-grid-filter @filterApplied"></button>
                    </div>
                </th>
                }
                else
                {
                <th class="@column.CssClasses @hidden"></th>
                }
            }
            </tr>
        }
        </thead>
        <tbody>
        @foreach (IGridRow<Object> row in Model.Rows)
        {
            <tr class="@row.CssClasses"@row.Attributes>
            @foreach (IGridColumn column in Model.Columns)
            {
                String classes = column.IsHidden ? column.CssClasses + " mvc-grid-hidden" : column.CssClasses;

                <td class="@classes">@column.ValueFor(row)</td>
            }
            </tr>
        }
        @if (!Model.Rows.Any() && Model.EmptyText != null)
        {
            <tr class="mvc-grid-empty-row">
                <td colspan="@Model.Columns.Count()">
                    @Model.EmptyText
                </td>
            </tr>
        }
</tbody>
    @if (Model.FooterPartialViewName != null)
    {
        <tfoot>
            @Html.Partial(Model.FooterPartialViewName, Model)
        </tfoot>
    }
    </table>
    @if (Model.Pager != null)
    {
        @Html.Partial(Model.Pager.PartialViewName, Model.Pager)
    }
</div>

src/HolidayLeave.Web/Views/Shared/MvcGrid/_Pager.cshtml
@using NonFactors.Mvc.Grid;
@model IGridPager
@{
    Int32 totalPages = Model.TotalPages;
    Int32 currentPage = Model.CurrentPage;
    Int32 firstDisplayPage = Model.FirstDisplayPage;
}
    <div class="mvc-grid-pager @Model.CssClasses" data-show-page-sizes="@Model.ShowPageSizes">
    @if (totalPages > 0)
    {
        if (currentPage > 1)
        {
        <button type="button" data-page="1">&#171;</button>
        <button type="button" data-page="@(currentPage - 1)">&#8249;</button>
        }
        else
        {
        <button type="button" class="disabled" tabindex="-1">&#171;</button>
        <button type="button" class="disabled" tabindex="-1">&#8249;</button>
        }
        for (Int32 page = firstDisplayPage; page <= totalPages && page < firstDisplayPage + Model.PagesToDisplay; page++)
        {
            if (page == currentPage)
            {
        <button type="button" class="active" data-page="@(page)">@(page)</button>
            }
            else
            {
        <button type="button" data-page="@(page)">@(page)</button>
            }
        }
        if (currentPage < totalPages)
        {
        <button type="button" data-page="@(currentPage + 1)">&#8250;</button>
        <button type="button" data-page="@totalPages">&#187;</button>
        }
        else
        {
        <button type="button" class="disabled" tabindex="-1">&#8250;</button>
        <button type="button" class="disabled" tabindex="-1">&#187;</button>
        }
        if (Model.ShowPageSizes)
        {
        <div class="mvc-grid-page-sizes">
        @if (Model.PageSizes.Count > 0)
        {
            <select class="mvc-grid-pager-rows">
            @foreach (KeyValuePair<Int32, String> size in Model.PageSizes)
            {
                if (Model.RowsPerPage == size.Key)
                {
                <option value="@size.Key" selected>@size.Value</option>
                }
                else
                {
                <option value="@size.Key">@size.Value</option>
                }
            }
            </select>
        }
        else
        {
            <input class="mvc-grid-pager-rows" value="@Model.RowsPerPage" />
        }
        </div>
        }
        else
        {
        <input class="mvc-grid-pager-rows" type="hidden" value="@Model.RowsPerPage" />
        }
    }
    else
    {
        <input class="mvc-grid-pager-rows" type="hidden" value="@Model.RowsPerPage" />
    }
    </div>

src/HolidayLeave.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/MvcGrid/mvc-grid.css")

</head>
<body>
    @Html.Partial("~/Views/Shared/_Message.cshtml")
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Urlopy", "Details", "HolidayLeave", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dodaj Urlop", "Create", "HolidayLeave")</li>
                    <li>@Html.ActionLink("Wynik", "Details", "HolidayLeave")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/Scripts/MvcGrid/mvc-grid.js")

    <script>
        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });

    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/HolidayLeave.Web/Views/Shared/_Message.cshtml
@if (TempData["TemporaryMessage"] != null)
{
    @Scripts.Render("~/Scripts/app/views/shared/showPopupMessage.js")
}

<div id="modalMessage" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content @TempData["TemporaryType"]" style="background-color: #97bbc9; ">
            <div class="modal-header @TempData["TemporaryType"]" role="alert">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Informacja</h4>
            </div>
            <div class="modal-body">
                <h3>@TempData["TemporaryMessage"]</h3>
            </div>
        </div>
    </div>
</div>